### ISSUE TITLE
貌似签到没加经验

### ISSUE THREAD

**Issue by EGo14T** [peizhouyu/tieba-sign#1]
关注了一个吧 正常应该签到直接到2级，使用这个脚本签到成功但是没有增加经验

**Comment by EGo14T** [comment]
PC签到加2经验。。

**Comment by peizhouyu** [comment]
> PC签到加2经验。。



> 关注了一个吧 正常应该签到直接到2级，使用这个脚本签到成功但是没有增加经验

这和脚本模拟PC 浏览器签到请求，我刚才去确认了下，果然PC端直接签到改变 +2，后续可以一起看看使用模拟移动客户端的方式签到，可以随时联系我

**Comment by EGo14T** [comment]
好的~
